# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set required vagrant version to run this vagrantfile
Vagrant.require_version ">= 1.4.3"
puppetlab_urls = Hash['centos_6' => 'https://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm', 'centos_7' => 'https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm', 'ubuntu_trusty64' => "NULL", 'ubuntu_xenial64' => "NULL"]
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
#puppetlab_urls = Hash.new("puppeturls")
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	["centos_6", "centos_7", "ubuntu_trusty64"].each do |i|  # Currently ubuntu_xenial64 not supported due to version issues in the puppetlabs-java module
	  config.vm.define "#{i}" do |node|
	    node.vm.box = "#{i.sub '_', '/'}"
	    node.vm.hostname = "takipi-dev"
	    node.vm.synced_folder ".", "/vagrant"
	    node.vm.synced_folder  "../", "/etc/puppet/modules/takipi" 
	    
	    # Provider-specific configuration so you can fine-tune various
	    # backing providers for Vagrant. These expose provider-specific options.
	    node.vm.provider "virtualbox" do |vb|
	      # Don't boot with headless mode
	      # vb.gui = true
	      
	      # specify vm name
	      vb.name = "takipi-#{i}-env"
	       
	      # Use VBoxManage to customize the VM. For example to change memory:
	      vb.customize ["modifyvm", :id, "--memory", "1024"]
	      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
	      
	      # The following allows symlinks in shared folders when running on windows host.
	      # vagrant must be run from a command prompt with admin privileges
	      if RUBY_PLATFORM == "i386-mingw32"
	        vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
	        vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/code", "1"]
	      end
	      
	    end
	    
	    if i.include? "centos"
	        node.vm.provision :shell, :path => "config_centos.sh", :args => puppetlab_urls[i]
	    elsif i.include? "ubuntu"
		node.vm.provision :shell, :path => "config_ubuntu.sh", :args => puppetlab_urls[i]
	    end

	    node.vm.provision :puppet do |puppet|
		puppet.manifest_file = "takipi.pp"
	    end
	
	  end

	end
end
